[platformio]
default_envs = uno

; --- AMBIENTE TRANSMISSOR (ARDUINO UNO) ---
[env:uno]
platform = atmelavr
board = uno
framework = arduino
monitor_speed = 9600
; O SEGREDO ESTÁ AQUI EMBAIXO:
build_src_filter = +<Transmissor/> -<Receptor/>
lib_deps =
    nrf24/RF24
    paulstoffregen/OneWire
    milesburton/DallasTemperature
    adafruit/DHT sensor library
    adafruit/Adafruit Unified Sensor

; --- AMBIENTE RECEPTOR (ESP32) ---
; --- AMBIENTE RECEPTOR (ESP8266) ---
[env:wemos_d1_uno32]
platform = espressif32
board = wemos_d1_uno32
framework = arduino
monitor_speed = 115200
monitor_filters = esp32_exception_decoder

build_src_filter = +<Receptor/> -<Transmissor/>

lib_deps = 
	nrf24/RF24 @ ^1.4.8
	arduino-libraries/ArduinoIoTCloud
	arduino-libraries/Arduino_ConnectionHandler
	marcoschwartz/LiquidCrystal_I2C @ ^1.1.4
	adafruit/Adafruit SSD1306 @ ^2.5.9
	adafruit/Adafruit GFX Library @ ^1.11.9
	adafruit/RTClib @ ^2.1.1 

lib_ignore =
	WiFiNINA
	WiFi101