[platformio]
default_envs = uno

; --- AMBIENTE TRANSMISSOR (ARDUINO UNO) ---
[env:uno]
platform = atmelavr
board = uno
framework = arduino
monitor_speed = 9600
; O SEGREDO ESTÁ AQUI EMBAIXO:
build_src_filter = +<Transmissor/> -<Receptor/>
lib_deps =
    nrf24/RF24
    paulstoffregen/OneWire
    milesburton/DallasTemperature
    adafruit/DHT sensor library
    adafruit/Adafruit Unified Sensor

; --- AMBIENTE RECEPTOR (ESP32) ---
; --- AMBIENTE RECEPTOR (ESP8266) ---
[env:esp8266]
; Vamos usar a plataforma estável padrão
platform = espressif8266
board = nodemcuv2
framework = arduino
monitor_speed = 115200

; Filtro de pastas
build_src_filter = +<Receptor/> -<Transmissor/>

; Aumenta o buffer para o Arduino Cloud não reclamar
build_flags = 
    -w
    -D PIO_FRAMEWORK_ARDUINO_ESPRESSIF_SDK22x_190703
    -D PIO_FRAMEWORK_ARDUINO_LWIP2_LOW_MEMORY

lib_deps =
    nrf24/RF24
    ; O PULO DO GATO: Travar em versões que funcionam
    arduino-libraries/ArduinoIoTCloud @ 1.13.0
    arduino-libraries/Arduino_ConnectionHandler @ 0.8.1
    ; Bibliotecas de tela
    marcoschwartz/LiquidCrystal_I2C
    adafruit/Adafruit SSD1306
    adafruit/Adafruit GFX Library