; ARQUIVO DE CONFIGURAÇÃO DO ARDUINO UNO (EMISSOR)
; Função: Ler sensores e enviar via Rádio NRF24

[env:uno]
platform = atmelavr
board = uno
framework = arduino

; Velocidade do Serial Monitor
monitor_speed = 9600

; A LISTA DE COMPRAS DO UNO
lib_deps =
    ; 1. Comunicação via Rádio (Essencial)
    nrf24/RF24

    ; 2. Sensores DS18B20 (Temperatura)
    paulstoffregen/OneWire
    milesburton/DallasTemperature

    ; 3. Sensor DHT (Umidade e Temperatura)
    adafruit/DHT sensor library
    adafruit/Adafruit Unified Sensor
    
    ; 4. Biblioteca para o Display LCD 16x2 (Se estiver no Uno)
    marcoschwartz/LiquidCrystal_I2C

; O Uno não precisa ignorar nada, ele é a base.